import type { EdgeKind, PilotbookConfig, TypeConfig } from "./types.ts";
import {
  ADR_STATUS,
  AREAS,
  BACKLOG_STATUS,
  BR_STATUS,
  IDEA_STATUS,
  PRIORITIES,
  SIZE,
} from "./types.ts";

function typeCfg(
  dir: string,
  prefix: string,
  pad: number,
  group: string,
  required: string[],
  extra: Partial<TypeConfig>,
): TypeConfig {
  const escaped = prefix.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  return {
    dir,
    prefix,
    pad,
    group,
    required,
    enums: extra.enums ?? {},
    arrays: extra.arrays ?? [],
    numbers: extra.numbers ?? [],
    dates: extra.dates ?? ["created", "updated"],
    objects: extra.objects ?? [],
    parent: extra.parent,
    template: extra.template ?? `${extra.parent ? "" : ""}${dir.split("/").pop()}.md`,
    idPattern: extra.idPattern ?? new RegExp(`^${escaped}\\d{${pad}}$`),
  };
}

export function builtinTypes(): Record<string, TypeConfig> {
  return {
    epic: typeCfg(
      "backlog/epics",
      "EPIC-",
      3,
      "backlog",
      [
        "id",
        "title",
        "type",
        "status",
        "priority",
        "estimate",
        "phase",
        "owner",
        "tags",
        "depends_on",
        "goal",
        "created",
        "updated",
      ],
      {
        enums: { type: ["epic"], status: [...BACKLOG_STATUS], priority: [...PRIORITIES] },
        arrays: ["tags", "depends_on"],
        numbers: ["estimate", "phase"],
        template: "epic.md",
      },
    ),
    story: typeCfg(
      "backlog/stories",
      "US-",
      3,
      "backlog",
      [
        "id",
        "title",
        "type",
        "epic",
        "status",
        "priority",
        "estimate",
        "phase",
        "owner",
        "tags",
        "depends_on",
        "business_rules",
        "adrs",
        "created",
        "updated",
      ],
      {
        enums: { type: ["story"], status: [...BACKLOG_STATUS], priority: [...PRIORITIES] },
        arrays: ["tags", "depends_on", "business_rules", "adrs"],
        numbers: ["estimate", "phase"],
        parent: "epic",
        template: "story.md",
      },
    ),
    task: typeCfg(
      "backlog/tasks",
      "TASK-",
      3,
      "backlog",
      [
        "id",
        "title",
        "type",
        "story",
        "status",
        "priority",
        "estimate",
        "phase",
        "owner",
        "area",
        "tags",
        "depends_on",
        "created",
        "updated",
      ],
      {
        enums: {
          type: ["task"],
          status: [...BACKLOG_STATUS],
          priority: [...PRIORITIES],
          area: [...AREAS],
        },
        arrays: ["tags", "depends_on"],
        numbers: ["estimate", "phase"],
        parent: "story",
        objects: ["verified"],
        template: "task.md",
      },
    ),
    adr: typeCfg(
      "adr",
      "ADR-",
      4,
      "knowledge",
      [
        "id",
        "title",
        "type",
        "status",
        "date",
        "deciders",
        "tags",
        "supersedes",
        "superseded_by",
        "created",
        "updated",
      ],
      {
        enums: { type: ["adr"], status: [...ADR_STATUS] },
        arrays: ["deciders", "tags", "supersedes", "superseded_by"],
        dates: ["date", "created", "updated"],
        template: "adr.md",
      },
    ),
    "business-rule": typeCfg(
      "business-rules",
      "BR-",
      3,
      "knowledge",
      [
        "id",
        "title",
        "type",
        "status",
        "domain",
        "version",
        "related",
        "tags",
        "created",
        "updated",
      ],
      {
        enums: { type: ["business-rule"], status: [...BR_STATUS] },
        arrays: ["related", "tags"],
        numbers: ["version"],
        template: "business-rule.md",
      },
    ),
    idea: typeCfg(
      "ideas",
      "IDEA-",
      3,
      "knowledge",
      [
        "id",
        "title",
        "type",
        "status",
        "impact",
        "effort",
        "promoted_to",
        "tags",
        "created",
        "updated",
      ],
      {
        enums: {
          type: ["idea"],
          status: [...IDEA_STATUS],
          impact: [...SIZE],
          effort: [...SIZE],
        },
        arrays: ["promoted_to", "tags"],
        template: "idea.md",
      },
    ),
  };
}

export function builtinEdges(): Record<string, EdgeKind> {
  return {
    depends_on: { to: ["epic", "story", "task"], blocking: true, acyclic: true },
    business_rules: { to: ["business-rule"], blocking: false, acyclic: false },
    adrs: { to: ["adr"], blocking: false, acyclic: false },
    related: { to: ["*"], blocking: false, acyclic: false },
    promoted_to: {
      to: ["epic", "story", "task", "business-rule", "adr"],
      blocking: false,
      acyclic: false,
    },
    supersedes: { to: ["adr"], blocking: false, acyclic: true },
    superseded_by: { to: ["adr"], blocking: false, acyclic: false },
    epic: { to: ["epic"], blocking: false, acyclic: false, scalar: true },
    story: { to: ["story"], blocking: false, acyclic: false, scalar: true },
  };
}

export function defaultConfig(): PilotbookConfig {
  return {
    name: "",
    root: "docs",
    board: "backlog/BOARD.md",
    cacheDir: ".pb",
    types: builtinTypes(),
    edges: builtinEdges(),
    codeMap: {},
    checks: { commands: [] },
    hooks: { blockOnUnverified: false },
    peers: [],
  };
}
